- name: Run database migrations
  command: "bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --env=prod chdir={{ deploy_helper.new_release_path }}"
  register: migrations
  failed_when: migrations.rc not in [0,255]

- name: make sure that all web writable folders exist
  file: path="{{ item.name }}" state=directory recurse=yes
  with_items: "{{ web_writable_folders }}"

- name: Set deploy_user ACL privileges on directories
  acl: name={{ item.name }} entity={{ deploy_user }} etype=user permissions=rwx state=present
  with_items: "{{ web_writable_folders }}"

- name: Set deploy_user default ACL privileges on directories
  acl: name={{ item.name }} entity={{ deploy_user }} etype=user permissions=rwx default=yes state=present
  with_items: "{{ web_writable_folders }}"

- name: Set web_user ACL privileges on directories
  acl: name={{ item.name }} entity={{ nginx_user }} etype=user permissions=rwx state=present
  with_items: "{{ web_writable_folders }}"

- name: Set web_user default ACL privileges on directories
  acl: name={{ item.name }} entity={{ nginx_user }} etype=user permissions=rwx default=yes state=present
  with_items: "{{ web_writable_folders }}"

- name: Clear cache
  command: "bin/console cache:clear --env=prod chdir={{ deploy_helper.new_release_path }}"
  register: cache
  failed_when: cache.rc not in [0,255]
