monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            excluded_404s:
                - ^/
            handler:      deduplicated
        deduplicated:
            type:    deduplication
            handler: symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: '%mailer_user%'
            to_email:   'markmeijerman@gmail.com'
            subject:    'Jurysteem PRODUCTION: An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
