monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        symfony_mailer:
            type: symfony_mailer
            from_email: '%mailer_user%'
            to_email: 'markmeijerman@gmail.com'
            subject: 'Jurysteem STAGING: An Error Occurred! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
