deploy_user: 'deploy'
nginx_user:  'www-data'
deploy_root: '/home/{{ deploy_user }}'

project_deploy_hook_on_finalize: "tasks/finalize_hooks.yml"

project_finalize: true
project_keep_releases: 3

project_command_for_composer_install: >
  composer install
  --no-ansi
  --no-dev
  --no-interaction
  --no-progress
  --optimize-autoloader
project_has_composer: yes

project_deploy_strategy: "git"
project_git_repo: "git@github.com:mjmeijerman/herstelkamer.nl.git"

project_templates:
  - name: Copy env file
    src: "{{ playbook_dir }}/templates/.env.j2"
    dest: ".env"

project_shared_children:
  - { path: "var/sessions", src: "sessions" }

web_writable_folders: []

project_environment:
  SYMFONY_ENV: "prod"
