deploy_user: 'deploy'
nginx_user:  'www-data'
deploy_root: '/home/{{ deploy_user }}'

project_deploy_hook_on_finalize: "tasks/finalize_hooks.yml"

project_finalize: true
project_keep_releases: 1

project_command_for_composer_install: >
  composer install
  --no-ansi
  --no-dev
  --no-interaction
  --no-progress
  --optimize-autoloader
  --no-scripts
project_has_composer: yes

project_deploy_strategy: "git"
project_git_repo: "git@github.com:mjmeijerman/herstelkamer.nl.git"

project_templates:
  - name: Copy env file
    src: "{{ playbook_dir }}/templates/.env.j2"
    dest: ".env"

project_shared_children:
  - { path: "var/sessions", src: "sessions" }

web_writable_folders:
  - { name: "{{ deploy_helper.new_release_path }}/var/cache", recursive: false }
  - { name: "{{ deploy_helper.new_release_path }}/var/log", recursive: false }
  - { name: "{{ deploy_helper.shared_path }}/sessions", recursive: false }
